#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define BOARD_LINES 14
#define BOARD_COLUMNS 14

#define POOL_SIZE 5

#define POOL_OFFSET_X 944
#define POOL_OFFSET_Y 38
#define POOL_SPACING 61
#define POOL_TOP_x 944
#define POOL_TOP_Y 312

#define INITIAL_TIMER 25
#define INITIAL_COLUMN 0
#define INITIAL_LINE   7
#define FINAL_COLUMN 13
#define FINAL_LINE   7

#define CRON_OFFSET_X 80
#define CRON_OFFSET_Y 80

#define SCORE_LABEL_OFFSET_X 65
#define SCORE_LABEL_OFFSET_Y 480
#define SCORE_OFFSET_X 65
#define SCORE_OFFSET_Y 500
#define SCORE_FONT_SIZE 20
#define GAME_OVER_OFFSET_X 400
#define GAME_OVER_OFFSET_Y 300
#define PLAY_AGAIN_OFFSET_X 400
#define PLAY_AGAIN_OFFSET_Y 350

#define BLOCKED_POSITIONS 70

#define START_MENU_OFFSET_X 450
#define START_MENU_OFFSET_Y 300
#define LEVEL_MENU_OFFSET_X 450
#define LEVEL_MENU_OFFSET_Y 350
#define EXIT_MENU_OFFSET_X 450
#define EXIT_MENU_OFFSET_Y 400

#define SELECT_LEVEL_OFFSET_X 450
#define SELECT_LEVEL_OFFSET_Y 250

#define LEVEL_EASY_OFFSET_X 450
#define LEVEL_EASY_OFFSET_Y 300
#define LEVEL_NORMAL_OFFSET_X 450
#define LEVEL_NORMAL_OFFSET_Y 350
#define LEVEL_HARD_OFFSET_X 450
#define LEVEL_HARD_OFFSET_Y 400

#define PLAY_AGAIN_YES_OFFSET_X 400
#define PLAY_AGAIN_YES_OFFSET_Y 400
#define PLAY_AGAIN_NO_OFFSET_X 400
#define PLAY_AGAIN_NO_OFFSET_Y 450

#define MENU_SIZE 30
#define MENU_HOVER_SIZE 40

enum eMenuOptions {
    // Nop
    MENU_NO_OP = 0,
    // start
    MENU_START_GAME,
    MENU_LEVEL,
    MENU_EXIT,
    // game over
    MENU_PLAY_AGAIN_YES,
    MENU_PLAY_AGAIN_NO,
    // select level
    MENU_LEVEL_EASY,
    MENU_LEVEL_NORMAL,
    MENU_LEVEL_HARD,
};

enum eLevel {
    LEVEL_EASY = 500,
    LEVEL_NORMAL = 250,
    LEVEL_HARD = 125,
};

#endif // DEFINES_H_INCLUDED
